name = "ops-api"
main = "src/index.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "http://localhost:5173,https://ops-web-siu.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "ops-db"
database_id = "b16cf57a-51d5-4e87-80ad-824180bebbcd"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "23330719c9714bc38202da39774a23a0"

[[r2_buckets]]
binding = "FILES"
bucket_name = "ops-files"
