// Sample data for Eternal Grace Hub prototype
// Storage-ready fields: audioUrl, coverUrl, posterUrl, downloadUrl all
// expected to point at Supabase Storage or another approved production object store.

window.EGH_DATA = {
  albums: [
    {
      slug: "alive-again",
      title: "Alive Again",
      artist: "Eternal Grace Music",
      year: 2025,
      scripture: "John 11:43–44",
      theme: "Resurrection · Hope · Mourning into Dancing",
      description:
        "Recorded over seven nights in a small chapel outside Asheville, Alive Again traces the path from the tomb to the table. Eleven songs for the seasons when faith feels heavy and the stone still hasn't moved.",
      coverLabel: "ALIVE AGAIN",
      coverHue: 200,
      runtime: "47:12",
      tracks: [
        { n: 1, title: "Come Forth", time: "4:12", key: "D",  lyric: "Out of the dark, the voice that made the morning\ncalling my name, calling my name —\nstone roll away, the linen falling,\nI walk into the day." },
        { n: 2, title: "Lazarus' Hymn",          time: "3:48", key: "G",  lyric: "Four days of silence, four days of stone.\nHe was not late. He was not late.\nI was already known." },
        { n: 3, title: "Bethany",                time: "5:01", key: "A",  lyric: "Sit with me, sister.\nSit with me, friend.\nHe is weeping with us\nbefore the end." },
        { n: 4, title: "Linen & Light",          time: "3:32", key: "Em", lyric: "Unbind him.\nLet him go.\nLet him go." },
        { n: 5, title: "Mary's Anointing",       time: "4:55", key: "C",  lyric: "The whole house with the perfume filled,\nwhat I had I poured —\npoured for the Lord." },
        { n: 6, title: "Garden Tomb",            time: "4:21", key: "Bm", lyric: "Why do you seek the living\namong the dead?" },
        { n: 7, title: "Mourning into Dancing",  time: "3:58", key: "D",  lyric: "You turned my mourning into dancing,\nyou clothed me with gladness —\nI will not be silent." },
        { n: 8, title: "Walk Out",               time: "4:07", key: "G",  lyric: "Walk out of the grave.\nWalk out of the grave." },
        { n: 9, title: "Table at Emmaus",        time: "5:14", key: "F",  lyric: "He broke the bread and we knew him,\nthen he was gone\nand our hearts burned on." },
        { n: 10, title: "Doxology (Reprise)",    time: "2:44", key: "D",  lyric: "Praise God from whom all blessings flow." },
        { n: 11, title: "Alive Again",           time: "5:00", key: "A",  lyric: "I was dead and now I'm living.\nI was lost and now I'm found.\nAlive again, alive again,\nmy feet upon the ground." },
      ],
    },
    {
      slug: "fire-from-heaven",
      title: "Fire From Heaven",
      artist: "Eternal Grace Music",
      year: 2024,
      scripture: "1 Kings 18:38",
      theme: "Revival · Prophetic courage · Consuming presence",
      description:
        "A live-tracked album about the cost and the call of the prophets. Recorded in a single overnight session with no overdubs — what you hear is the room.",
      coverLabel: "FIRE FROM HEAVEN",
      coverHue: 28,
      runtime: "52:38",
      tracks: [
        { n: 1, title: "Carmel",          time: "5:22", key: "Em", lyric: "Twelve stones for the broken altar,\ntwelve stones for the name —\nthe water poured, the trench is full,\nbring down the flame." },
        { n: 2, title: "How Long Will You Halt", time: "4:11", key: "Am", lyric: "How long will you halt\nbetween two opinions?\nIf the Lord is God,\nfollow him." },
        { n: 3, title: "Elijah's Prayer", time: "3:44", key: "G",  lyric: "Hear me, O Lord, hear me,\nthat this people may know\nthat thou art God." },
        { n: 4, title: "The Trench",      time: "4:48", key: "Dm", lyric: "Pour it again.\nPour it again.\nWhat is impossible to dry kindling\nis nothing to the wind." },
        { n: 5, title: "Consume",         time: "5:09", key: "Bm", lyric: "It fell, it fell,\nfire from heaven fell —\nstone and water, dust and all,\nconsumed, consumed." },
        { n: 6, title: "Brook Cherith",   time: "4:33", key: "C",  lyric: "Hidden by the brook,\nfed by the ravens —\nyou keep me when you hide me." },
        { n: 7, title: "Still Small Voice", time: "5:50", key: "F", lyric: "Not in the wind.\nNot in the earthquake.\nNot in the fire.\nA whisper." },
        { n: 8, title: "Mantle",          time: "3:55", key: "G",  lyric: "Let a double portion\nfall on me." },
        { n: 9, title: "Chariots",        time: "4:21", key: "Em", lyric: "Horses of fire,\nchariots of fire —\nmy father, my father,\nthe chariots of Israel." },
        { n: 10, title: "Send the Rain",  time: "5:30", key: "D",  lyric: "There is a sound\nof abundance of rain." },
        { n: 11, title: "Fire From Heaven (Reprise)", time: "5:15", key: "Em", lyric: "Fall again.\nFall again." },
      ],
    },
    {
      slug: "the-giant-falls",
      title: "The Giant Falls",
      artist: "Eternal Grace Music",
      year: 2023,
      scripture: "1 Samuel 17:49",
      theme: "Courage · Small stones · The Lord saves not by sword",
      description:
        "Anthems for the valley. Twelve tracks for anyone facing a giant — written for the ones who can't wear the armor anyone else is offering.",
      coverLabel: "THE GIANT FALLS",
      coverHue: 350,
      runtime: "44:19",
      tracks: [
        { n: 1, title: "Valley of Elah",   time: "4:02", key: "A",  lyric: "Forty days, forty nights,\nthe armies stood still —\nbut a shepherd boy came down\nto the valley with his sling." },
        { n: 2, title: "Five Smooth Stones", time: "3:38", key: "D", lyric: "Five smooth stones from the brook,\none was enough,\nbut I will not be caught\nwithout my five." },
        { n: 3, title: "Not By the Sword", time: "4:21", key: "G",  lyric: "Not by the sword, not by the spear —\nthe battle belongs\nto the Lord." },
        { n: 4, title: "Goliath's Boast",  time: "3:11", key: "Em", lyric: "Am I a dog, that you come with sticks?\nI will give your flesh to the birds." },
        { n: 5, title: "Armor Off",        time: "4:44", key: "C",  lyric: "I have not proved them.\nI cannot go in these.\nTake the armor off,\ntake the armor off." },
        { n: 6, title: "Shepherd's Sling", time: "3:55", key: "F",  lyric: "From the lion, from the bear,\nthe Lord has delivered me —\nand he will deliver me\nfrom this Philistine." },
        { n: 7, title: "The Giant Falls",  time: "4:28", key: "A",  lyric: "And the stone sank into his forehead,\nand he fell on his face,\nand the giant falls,\nand the giant falls." },
        { n: 8, title: "Brook of Courage", time: "3:42", key: "G",  lyric: "Reach into the water,\npull out what is small —\nGod has been training you\nfor a giant after all." },
        { n: 9, title: "Saul Watches",     time: "4:13", key: "Bm", lyric: "Whose son is this young man?\nWhose son?\nWhose son?" },
        { n: 10, title: "Song of the Sling", time: "3:21", key: "D", lyric: "One stone, one breath,\none name to call." },
        { n: 11, title: "Valley to the Throne", time: "5:04", key: "A", lyric: "From the valley to the throne,\nfrom the sheepfold to the song —\nthe Lord lifts up the lowly,\nthe Lord makes the weak strong." },
        { n: 12, title: "Doxology (Stone)", time: "2:40", key: "D",  lyric: "Praise God from whom all blessings flow." },
      ],
    },
    {
      slug: "bread-in-the-wilderness",
      title: "Bread in the Wilderness",
      artist: "Eternal Grace Music",
      year: 2026,
      scripture: "Exodus 16:4",
      theme: "Provision - Trust - Daily bread",
      description:
        "A quiet record for lean seasons, built around the mercy of manna and the faith to gather enough for today.",
      coverLabel: "BREAD IN THE WILDERNESS",
      coverHue: 86,
      runtime: "39:28",
      tracks: [
        { n: 1, title: "Morning Manna", time: "4:18", key: "G", lyric: "Give us this day our daily bread." },
        { n: 2, title: "Enough for Today", time: "3:54", key: "D", lyric: "Your mercy is new with the morning." },
        { n: 3, title: "Quail at Evening", time: "4:36", key: "Em", lyric: "At evening we remember your hand." },
        { n: 4, title: "Cloud and Fire", time: "5:02", key: "C", lyric: "Lead us by cloud, guard us by flame." },
        { n: 5, title: "No Lack", time: "4:11", key: "A", lyric: "There was no lack among your people." },
        { n: 6, title: "Sabbath Rest", time: "5:20", key: "F", lyric: "Teach our hands to cease." },
        { n: 7, title: "Gather Again", time: "4:27", key: "D", lyric: "We gather grace from the ground." },
        { n: 8, title: "The Bread of Heaven", time: "7:40", key: "G", lyric: "Bread of heaven, feed us till we want no more." },
      ],
    },
    {
      slug: "songs-of-deliverance",
      title: "Songs of Deliverance",
      artist: "Eternal Grace Music",
      year: 2026,
      scripture: "Psalm 32:7",
      theme: "Rescue - Refuge - Freedom",
      description:
        "A bright worship collection for testimony nights, prayer gatherings, and the long road out of fear.",
      coverLabel: "SONGS OF DELIVERANCE",
      coverHue: 154,
      runtime: "42:05",
      tracks: [
        { n: 1, title: "Hiding Place", time: "4:40", key: "C", lyric: "You are my hiding place." },
        { n: 2, title: "Surrounded by Songs", time: "3:58", key: "G", lyric: "You surround me with deliverance." },
        { n: 3, title: "Out of the Net", time: "4:22", key: "D", lyric: "The snare is broken and we have escaped." },
        { n: 4, title: "Refuge", time: "5:11", key: "A", lyric: "Under your wings I will trust." },
        { n: 5, title: "Chains Fall", time: "4:03", key: "Em", lyric: "Where the Spirit is, there is liberty." },
        { n: 6, title: "The Door Was Open", time: "5:26", key: "F", lyric: "The iron gate opened of its own accord." },
        { n: 7, title: "Free Indeed", time: "4:49", key: "G", lyric: "Whom the Son sets free is free indeed." },
        { n: 8, title: "New Song", time: "9:36", key: "D", lyric: "He put a new song in my mouth." },
      ],
    },
    {
      slug: "mercy-at-the-well",
      title: "Mercy at the Well",
      artist: "Eternal Grace Music",
      year: 2025,
      scripture: "John 4:14",
      theme: "Living water - Mercy - Witness",
      description:
        "Songs for the thirsty heart, centered on the Samaritan woman and the Savior who meets us in plain daylight.",
      coverLabel: "MERCY AT THE WELL",
      coverHue: 218,
      runtime: "36:52",
      tracks: [
        { n: 1, title: "At Jacob's Well", time: "4:12", key: "D", lyric: "He sat by the well and waited." },
        { n: 2, title: "Living Water", time: "5:04", key: "G", lyric: "Spring up in me, living water." },
        { n: 3, title: "Noon Day Mercy", time: "3:49", key: "C", lyric: "Mercy found me at noon." },
        { n: 4, title: "I Who Speak", time: "4:45", key: "Em", lyric: "I who speak to thee am he." },
        { n: 5, title: "Leave the Jar", time: "3:36", key: "A", lyric: "I left my waterpot behind." },
        { n: 6, title: "Come and See", time: "4:58", key: "F", lyric: "Come see a man who told me all things." },
        { n: 7, title: "Fields Are White", time: "5:18", key: "D", lyric: "Lift up your eyes to the harvest." },
        { n: 8, title: "Worship in Spirit", time: "5:10", key: "G", lyric: "In spirit and truth we worship." },
      ],
    },
    {
      slug: "night-watch-psalms",
      title: "Night Watch Psalms",
      artist: "Eternal Grace Music",
      year: 2024,
      scripture: "Psalm 63:6",
      theme: "Prayer - Watchfulness - Peace",
      description:
        "A late-night record for prayer rooms, quiet homes, and everyone learning to remember God upon the bed.",
      coverLabel: "NIGHT WATCH PSALMS",
      coverHue: 268,
      runtime: "41:33",
      tracks: [
        { n: 1, title: "Upon My Bed", time: "4:20", key: "Em", lyric: "I remember thee upon my bed." },
        { n: 2, title: "Watches of the Night", time: "5:14", key: "D", lyric: "In the watches of the night, you are near." },
        { n: 3, title: "Keep My Soul", time: "4:01", key: "G", lyric: "Keep my soul in peace." },
        { n: 4, title: "Lamp for My Feet", time: "3:58", key: "C", lyric: "Your word is a lamp unto my feet." },
        { n: 5, title: "Selah", time: "4:43", key: "F", lyric: "Be still before the Lord." },
        { n: 6, title: "Songs in the Night", time: "5:07", key: "A", lyric: "You give songs in the night." },
        { n: 7, title: "Peace Like a Guard", time: "4:36", key: "D", lyric: "Let peace guard my heart." },
        { n: 8, title: "Till Morning Comes", time: "9:34", key: "G", lyric: "We wait for the morning light." },
      ],
    },
  ],

  videos: [
    {
      slug: "lazarus-alive-again",
      title: "Lazarus: Alive Again",
      testament: "New Testament",
      book: "John",
      passage: "John 11",
      runtime: "18:42",
      year: 2025,
      hue: 200,
      summary:
        "Jesus arrives in Bethany four days after the funeral. The story of Lazarus, Mary, Martha, and the moment a stone rolled away.",
      themes: ["Resurrection", "Grief", "Friendship", "Miracle"],
      chapters: [
        { t: "00:00", title: "Bethany, four days later" },
        { t: "03:14", title: "Martha meets the road" },
        { t: "06:48", title: "Mary at his feet" },
        { t: "10:02", title: "Jesus wept" },
        { t: "13:17", title: "The stone" },
        { t: "15:55", title: "Come forth" },
      ],
      relatedAlbum: "alive-again",
    },
    {
      slug: "elijah-fire-from-heaven",
      title: "Elijah: Fire From Heaven",
      testament: "Old Testament",
      book: "1 Kings",
      passage: "1 Kings 18",
      runtime: "22:08",
      year: 2024,
      hue: 28,
      summary:
        "A drought-stricken Israel. 450 prophets of Baal. One prophet of the Lord, twelve stones, and a trench full of water on Mount Carmel.",
      themes: ["Revival", "Courage", "Confrontation", "Prophecy"],
      chapters: [
        { t: "00:00", title: "Three years without rain" },
        { t: "04:01", title: "Obadiah in the cave" },
        { t: "07:30", title: "The challenge at Carmel" },
        { t: "11:12", title: "Baal answers not" },
        { t: "15:40", title: "Twelve stones, four jars" },
        { t: "19:22", title: "The fire falls" },
      ],
      relatedAlbum: "fire-from-heaven",
    },
    {
      slug: "david-and-goliath",
      title: "David and Goliath",
      testament: "Old Testament",
      book: "1 Samuel",
      passage: "1 Samuel 17",
      runtime: "19:55",
      year: 2023,
      hue: 350,
      summary:
        "A shepherd boy with five smooth stones walks into the valley of Elah and changes the war. Goliath is taller than the story you remember.",
      themes: ["Courage", "Faith", "Small things", "Valley"],
      chapters: [
        { t: "00:00", title: "Valley of Elah" },
        { t: "03:22", title: "Forty days of dread" },
        { t: "06:55", title: "A boy with bread and cheese" },
        { t: "10:10", title: "Saul's armor" },
        { t: "13:48", title: "Five smooth stones" },
        { t: "17:00", title: "The giant falls" },
      ],
      relatedAlbum: "the-giant-falls",
    },
    {
      slug: "esther-for-such-a-time",
      title: "Esther: For Such a Time",
      testament: "Old Testament",
      book: "Esther",
      passage: "Esther 4",
      runtime: "21:30",
      year: 2025,
      hue: 320,
      summary:
        "A Jewish orphan becomes queen of Persia. Mordecai's question still hangs in the air: who knows whether you have come for such a time as this?",
      themes: ["Courage", "Providence", "Identity"],
      chapters: [
        { t: "00:00", title: "Susa" },
        { t: "04:30", title: "The decree" },
        { t: "09:00", title: "Mordecai at the gate" },
        { t: "13:15", title: "If I perish, I perish" },
        { t: "17:40", title: "The banquet" },
      ],
      relatedAlbum: null,
    },
    {
      slug: "ruth-the-redeemer",
      title: "Ruth: The Redeemer",
      testament: "Old Testament",
      book: "Ruth",
      passage: "Ruth 1–4",
      runtime: "16:14",
      year: 2024,
      hue: 38,
      summary:
        "Whither thou goest, I will go. A Moabite widow follows her mother-in-law into a foreign land and finds a redeemer in a barley field.",
      themes: ["Loyalty", "Loss", "Redemption"],
      chapters: [
        { t: "00:00", title: "The road from Moab" },
        { t: "03:50", title: "Naomi, call me Mara" },
        { t: "06:42", title: "Gleaning in Boaz's field" },
        { t: "10:08", title: "At his feet" },
        { t: "13:12", title: "Kinsman redeemer" },
      ],
      relatedAlbum: null,
    },
    {
      slug: "jonah-and-the-fish",
      title: "Jonah and the Fish",
      testament: "Old Testament",
      book: "Jonah",
      passage: "Jonah 1–4",
      runtime: "17:22",
      year: 2023,
      hue: 180,
      summary:
        "A reluctant prophet, a storm, a great fish, and a city given another chance. The story is not really about the fish.",
      themes: ["Repentance", "Mercy", "Mission"],
      chapters: [
        { t: "00:00", title: "Tarshish, the other way" },
        { t: "04:00", title: "Cast me into the sea" },
        { t: "07:45", title: "Three days, three nights" },
        { t: "11:30", title: "Nineveh repents" },
        { t: "14:50", title: "The withered vine" },
      ],
      relatedAlbum: null,
    },
  ],

  products: [
    {
      slug: "alive-again-digital-bundle",
      title: "Alive Again — Digital Album Bundle",
      kind: "bundle",
      price: 14,
      includes: ["FLAC + MP3 album", "Lyric PDF (44 pages)", "Chord book PDF (84 pages)", "Cover art (print-ready)"],
      blurb: "Everything from the Alive Again record, in one tidy folder.",
      checkoutUrl: "#/checkout/alive-again-digital-bundle",
      tag: "Best for fans",
      hue: 200,
    },
    {
      slug: "fire-from-heaven-chord-book",
      title: "Fire From Heaven — Chord Book",
      kind: "chord-book",
      price: 9,
      includes: ["Full chord charts for all 11 tracks", "Capo + transposed keys", "Letter & A4 print sizes"],
      blurb: "Everything a worship leader needs to lead the record from stage.",
      checkoutUrl: "#/checkout/fire-from-heaven-chord-book",
      hue: 28,
    },
    {
      slug: "the-giant-falls-lyrics-pdf",
      title: "The Giant Falls — Lyrics PDF",
      kind: "lyrics",
      price: 5,
      includes: ["All 12 tracks, typeset", "Scripture references", "Letter & A4 print sizes"],
      blurb: "A clean, readable lyric book for personal worship or projection.",
      checkoutUrl: "#/checkout/the-giant-falls-lyrics-pdf",
      hue: 350,
    },
    {
      slug: "worship-leader-bundle",
      title: "Worship Leader Bundle (All 3 Albums)",
      kind: "bundle",
      price: 39,
      includes: ["All 3 chord books", "All 3 lyric PDFs", "Multi-track stems (where available)", "Pro Presenter loops"],
      blurb: "Lead any night of worship from any of our records.",
      checkoutUrl: "#/checkout/worship-leader-bundle",
      tag: "For worship leaders",
      hue: 42,
    },
    {
      slug: "free-scripture-pack",
      title: "Free — Scripture Reading Pack",
      kind: "free",
      price: 0,
      includes: ["6 single-page PDFs (one per video)", "Printable scripture cards"],
      blurb: "Read along with the BibleInVideo stories. Free, always.",
      checkoutUrl: "#/checkout/free-scripture-pack",
      tag: "Free",
      hue: 180,
    },
    {
      slug: "free-doxology-chord-sheet",
      title: "Free — Doxology (chord sheet)",
      kind: "free",
      price: 0,
      includes: ["1 chord sheet, both reprises", "Letter & A4"],
      blurb: "The two Doxology reprises from our records, in your hymnbook.",
      checkoutUrl: "#/checkout/free-doxology-chord-sheet",
      tag: "Free",
      hue: 38,
    },
    {
      slug: "bread-in-the-wilderness-chord-book",
      title: "Bread in the Wilderness - Chord Book",
      kind: "chord-book",
      price: 9,
      includes: ["All 8 songs", "Capo-friendly keys", "Letter & A4 print sizes"],
      blurb: "A warm chord book for leading songs of provision, trust, and daily bread.",
      checkoutUrl: "#/checkout/bread-in-the-wilderness-chord-book",
      hue: 86,
    },
    {
      slug: "mercy-at-the-well-digital-bundle",
      title: "Mercy at the Well - Digital Bundle",
      kind: "bundle",
      price: 14,
      includes: ["MP3 album", "Lyrics PDF", "Chord book PDF"],
      blurb: "Audio, lyrics, and chords for a worship set centered on living water.",
      checkoutUrl: "#/checkout/mercy-at-the-well-digital-bundle",
      tag: "New",
      hue: 218,
    },
    {
      slug: "night-watch-psalms-lyrics-pdf",
      title: "Night Watch Psalms - Lyrics PDF",
      kind: "lyrics",
      price: 5,
      includes: ["All 8 songs", "Prayer-room format", "Letter & A4 print sizes"],
      blurb: "A quiet lyric book for late-night prayer, reflection, and projection.",
      checkoutUrl: "#/checkout/night-watch-psalms-lyrics-pdf",
      hue: 268,
    },
  ],
};
